#this scenario will be executed in case of creation of a Pull Request
name: pull request logic



  

on:
  push:
    #PR target branch is: 
    branches:
      - 'main**'


jobs:
  doom:
    name: doom
    runs-on: ubuntu-latest
    steps:

      - name: --- System Step 0 ---. Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



      - name: --- System Step 3 ---. run JEST tests
        run: |
            HOME_DIR=$(pwd)
            echo -e "--- STEP 0 ---\n\n"
            ls -a -l
            echo -e "\n\n --- STEP 0 ---"


            cd src && make

            echo -e "--- STEP 1 ---\n\n"
            cd $HOME_DIR
            ls -a
            echo -e "\n\n --- STEP 1 ---"




            echo -e "--- STEP 2 ---\n\n"
            mv DOOM1.WAD ./doom_ascii

            cd doom_ascii
            ls -a -l
            echo -e "--- STEP 2 ---\n\n"




            echo -e "--- STEP 2 ---\n\n"
            chmod +x ./doom_ascii/doom_ascii
            ./doom_ascii/doom_ascii
            echo -e "--- STEP 2 ---\n\n"