#this scenario will be executed in case of creation of a Pull Request
name: pull request logic



  

on:
  push:
    #PR target branch is: 
    branches:
      - 'main**'


jobs:
  doom:
    name: doom
    runs-on: ubuntu-latest
    steps:

      - name: --- System Step 0 ---. Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



      - name: --- System Step 3 ---. run JEST tests
        run: |
            HOME_DIR=$(pwd)
            cd src && make