#this scenario will be executed in case of creation of a Pull Request
name: pull request logic



  

on:
  push:
    #PR target branch is: 
    branches:
      - 'main**'


jobs:
  doom:
    name: doom
    runs-on: ubuntu-latest
    steps:

      - name: --- System Step 0 ---. Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



      - name: --- System Step 3 ---. run JEST tests
        run: |
            HOME_DIR=$(pwd)
            cd src && make

            echo -e "--- STEP 1 ---\n\n"
            cd $HOME_DIR
            ls -a
            echo -e "\n\n --- STEP 1 ---"


            wget https://archive.org/download/2020_03_22_DOOM/DOOM%20WADs/Doom%20%28v1.9%29%20%28Demo%29.zip


            echo -e "--- STEP 2 ---\n\n"
            echo "ZIP archive is there?"
            ls -a
            echo "----------------"
            cd doom_ascii
            ls -a
            cd $HOME_DIR
            echo -e "\n\n --- STEP 2 ---"



            unzip Doom\ \(v1.9\)\ \(Demo\).zip -d $HOME_DIR/doom-ascii/


            echo -e "--- STEP 3 ---\n\n"
            cd doom_ascii/doom_ascii
            ls -a
            cd $HOME_DIR
            echo -e "\n\n --- STEP 3 ---"